# Generated by Django 4.0.3 on 2022-05-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_prod_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod',
            name='image',
            field=models.ImageField(default='', upload_to='media/images'),
        ),
    ]
